version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-node
    working_directory: ~/singnet/marketplace
    environment:
      TRIGGER_BUILD_BRANCH: master
    steps:
      - run:
          name: Install all the dependencies
          command: |
              sudo apt-get update
              sudo apt-get install python3-pip
      - checkout
      - run:
          name: Build the marketplace
          command: |
              pip3 install -r requirement.txt -t .
              sudo python3 -m compileall *.py
  post_build:
    docker:
      - image: circleci/python:3.6.6-node
    working_directory: ~/singnet/marketplace
    environment:
      TRIGGER_BUILD_BRANCH: master
    steps:
      - run:
          name: Trigger platform-pipeline build
          command: |
              if [ "$CIRCLE_BRANCH" == "$TRIGGER_BUILD_BRANCH" ]
              then
                echo "Triggering Pipeline Project"
                #curl -u ${CIRCLECI_PLATFORM_PIPELINE_TOKEN}: \
                #  -d build_parameters[CIRCLE_JOB]=build \
                #  -d build_parameters[PARENT_PROJECT_REPONAME]="$CIRCLE_PROJECT_REPONAME" \
                #  -d build_parameters[PARENT_BRANCH]="$CIRCLE_BRANCH" \
                #  -d build_parameters[PARENT_BUILD_URL]="$CIRCLE_BUILD_URL" \
                #  https://circleci.com/api/v1.1/project/github/singnet/platform-pipeline/tree/${TRIGGER_BUILD_BRANCH}
              fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - post_build
	  requires:
	    - build

